export interface FieldsPattern {
  fieldId: number,
  fieldStatus: "disabled" | "empty" | "building" | "grow" | "harvest",
  fieldCrop: string;
}

export const fields: FieldsPattern[] = [
  { fieldId: 0, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 1, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 2, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 3, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 4, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 5, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 6, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 7, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 8, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 9, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 10, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 11, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 12, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 13, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 14, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 15, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 16, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 17, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 18, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 19, fieldStatus: "empty", fieldCrop: "none" },
  { fieldId: 20, fieldStatus: "empty", fieldCrop: "none" },
  { fieldId: 21, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 22, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 23, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 24, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 25, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 26, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 27, fieldStatus: "empty", fieldCrop: "none" },
  { fieldId: 28, fieldStatus: "empty", fieldCrop: "none" },
  { fieldId: 29, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 30, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 31, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 32, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 33, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 34, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 35, fieldStatus: "empty", fieldCrop: "none" },
  { fieldId: 36, fieldStatus: "empty", fieldCrop: "none" },
  { fieldId: 37, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 38, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 39, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 40, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 41, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 42, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 43, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 44, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 45, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 46, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 47, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 48, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 49, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 50, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 51, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 52, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 53, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 54, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 55, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 56, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 57, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 58, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 59, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 60, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 61, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 62, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 63, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 64, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 65, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 66, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 67, fieldStatus: "disabled", fieldCrop: "none" },
  { fieldId: 68, fieldStatus: "disabled", fieldCrop: "none" }
];